require:
  - rubocop-rails

AllCops:
 TargetRubyVersion: 2.7.2
 SuggestExtensions: false
 NewCops: enable
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'
   - 'spec/spec_helper.rb'
   - 'node_modules/**/*'
   - 'app/controllers/professionals/**/*'
   - 'app/controllers/users/**/*'
   - 'Gemfile.lock'

Style/FrozenStringLiteralComment:
 Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
 IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']

Layout/LineLength:
  Max: 80
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
